apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: CD-with-Argo
spec:
  destination:
    server: 'https://kubernetes.default.svc'  # Correcto, porque Argo CD está dentro del clúster
    namespace: default
  source:
    repoURL: 'https://github.com/daniel2688/ArgoCD-test.git'
    path: nginx-deployment
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true